import { sql } from "@vercel/postgres";
import type { ArMarketSnapshot, ArMarketSnapshotScope, ArMarketNarrative } from "@discografica/shared/types/ar";

let ready: Promise<void> | null = null;

// The module's rotating "what's happening" summary — regenerated by
// generateMarketSnapshot() (lib/arMarketIntelligence.ts), never computed
// here. data_snapshot is an audit trail of the real numbers the narrative
// was grounded in, kept alongside it so a claim in the text can always be
// checked against what was actually fed to the model.
export function ensureArMarketSnapshotsSchema(): Promise<void> {
  if (!ready) {
    ready = (async () => {
      await sql`
        CREATE TABLE IF NOT EXISTS ar_market_snapshots (
          id BIGSERIAL PRIMARY KEY,
          scope TEXT NOT NULL,
          narrative JSONB NOT NULL,
          data_snapshot JSONB NOT NULL,
          generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          generated_by TEXT,
          model TEXT NOT NULL
        )
      `;
      await sql`CREATE INDEX IF NOT EXISTS ar_market_snapshots_scope_idx ON ar_market_snapshots (scope, generated_at DESC)`;
    })();
  }
  return ready;
}

function rowToSnapshot(r: Record<string, unknown>): ArMarketSnapshot {
  return {
    id: Number(r.id),
    scope: r.scope as ArMarketSnapshotScope,
    narrative: r.narrative as ArMarketNarrative,
    dataSnapshot: r.data_snapshot as Record<string, unknown>,
    generatedAt: r.generated_at as string,
    generatedBy: (r.generated_by as string | null) ?? null,
    model: r.model as string,
  };
}

export async function getLatestMarketSnapshot(scope: ArMarketSnapshotScope = "combined"): Promise<ArMarketSnapshot | null> {
  await ensureArMarketSnapshotsSchema();
  const { rows } = await sql`
    SELECT * FROM ar_market_snapshots WHERE scope = ${scope} ORDER BY generated_at DESC LIMIT 1
  `;
  return rows[0] ? rowToSnapshot(rows[0]) : null;
}

export async function createMarketSnapshot(input: {
  scope: ArMarketSnapshotScope;
  narrative: ArMarketNarrative;
  dataSnapshot: Record<string, unknown>;
  generatedBy: string | null;
  model: string;
}): Promise<ArMarketSnapshot> {
  await ensureArMarketSnapshotsSchema();
  const { rows } = await sql`
    INSERT INTO ar_market_snapshots (scope, narrative, data_snapshot, generated_by, model)
    VALUES (${input.scope}, ${JSON.stringify(input.narrative)}::jsonb, ${JSON.stringify(input.dataSnapshot)}::jsonb, ${input.generatedBy}, ${input.model})
    RETURNING *
  `;
  return rowToSnapshot(rows[0]);
}
